[package]
name = "carteira-de-investimentos-maicaosa"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
argon2 = "0.5.3"
axum = "0.8.9"
dotenvy = "0.15.7"
hmac = "0.13.0"
hex = "0.4.3"
jsonwebtoken = { version = "11.0.0", features = ["rust_crypto"] }
rand_core = { version = "0.6.4", features = ["getrandom"] }
rust_decimal = { version = "1.39.0", features = ["serde-with-str"] }
serde = { version = "1.0.229", features = ["derive"] }
sha2 = "0.11.0"
sqlx = { version = "0.9.0", features = ["runtime-tokio", "tls-rustls-ring", "postgres", "uuid", "time", "rust_decimal", "migrate"] }
thiserror = "2.0.19"
time = "0.3.54"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "net", "signal", "sync", "time"] }
tower-http = { version = "0.7.0", features = ["trace", "request-id", "timeout", "limit"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
uuid = { version = "1.24.0", features = ["v4", "serde"] }

[dev-dependencies]
rust_decimal_macros = "1.39.0"
